export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_LOCALIZATION = "SET_LOCALIZATION";
export const SET_CITIZENSHIP = "SET_CITIZENSHIP";
export const SET_DESTINATIONS = "SET_DESTINATIONS";
export const SET_ENTRY_REQUIREMENTS = "SET_ENTRY_REQUIREMENTS";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
